// Auto-generated banks for generate-messages.js (from existing locale samples)

export const DIFFICULTY_DESCRIPTIONS = {
  en: {"easy": "An introductory puzzle that teaches you the basic sliding mechanics. Take your time to understand how blocks move through the gates.", "medium": "A balanced puzzle that requires planning a few moves ahead. Look for the gate order before you start moving blocks.", "hard": "A challenging level with multiple block types and tight space. Wrong moves can box you in — visualize the full sequence first.", "expert": "An advanced level with overlapping pieces and complex routing. Solving it cleanly often requires moving blocks out of the way and back.", "super-hard": "A super-hard level designed to push your spatial reasoning. Expect to retry several times — and use the video to confirm the optimal opening."},
  cn: {"easy": "入门关卡，帮你熟悉滑动机制。慢慢观察方块如何穿过对应颜色的门。", "medium": "中等难度，需要提前规划几步。先看清出口顺序，再开始移动方块。", "hard": "高难度关卡，方块类型多、空间紧。错一步就会卡住，先在脑子里走完整套流程。", "expert": "进阶关卡，方块互相阻挡、路径复杂。常常需要先把碍事的方块挪开再放回去。", "super-hard": "超高难度，专门考验空间想象力。多试几次没关系，配合视频确认起手最优解。"},
  ja: {"easy": "基本のスライド操作を覚えるための入門ステージ。ブロックが扉を通る感覚を確かめましょう。", "medium": "中級ステージ。数手先まで読んで動かす必要があります。先に扉の順番を確認しましょう。", "hard": "ブロックの種類が多く、空間も狭い高難度ステージ。動かす順番を頭の中で組み立ててから始めましょう。", "expert": "上級者向けステージ。重なり合うブロックを退避させて戻す手順が必要です。", "super-hard": "空間認識力を試す超高難度。何度も挑戦し、動画で最適な初手を確認してください。"},
};

export const TIPS_BANK = {
  en: {"easy": ["Identify each block's color and find the matching gate before you move anything.", "Move smaller blocks first to free up space for larger pieces.", "Watch for blocks that share an exit — those usually need to leave in a specific order.", "If you get stuck, undo and retrace the gate sequence from the bottom up."], "medium": ["Plan three moves ahead before sliding the first block.", "Treat blocking pieces as 'parking' — slide them out of the way temporarily.", "L-shaped and T-shaped blocks usually rotate the puzzle's logic — solve around them first.", "When two colors race for the same lane, pick the one whose path is fully open.", "Use the preview to confirm a block actually fits its target gate before committing."], "hard": ["Map out the full evacuation order for every gate before your first move.", "Long pieces need a clear runway — clear horizontal or vertical space first.", "If a block can only exit through one path, leave that path empty until the end.", "Don't be afraid to backtrack a block one or two squares to unblock another.", "Save the 'pivot' piece — the one in the densest corner — for last."], "expert": ["Identify the choke point on the board and treat it as your bottleneck — sequence around it.", "Some blocks must be moved twice: once to clear a path, then back to their gate.", "Watch the video at 0.5x speed to catch micro-moves that look like one slide.", "If two pieces have only one viable exit each, there's usually only one correct order.", "Reset early if your first 4 moves don't match the optimal opening — you'll save time."], "super-hard": ["Pause the video frame-by-frame on the first 5 moves — those define the entire solution.", "Identify the 'lock' piece (the one that traps everything) and figure out when it can move.", "Many super-hard levels need a piece to traverse the entire board twice. Plan the round trip.", "If you get stuck halfway through, the failure is usually in moves 2 or 3, not move 10.", "Treat each color as a thread — solve them in dependency order, not visual order."]},
  cn: {"easy": ["先看清每个方块的颜色，找到对应的出口门，再开始移动。", "先移动小方块，给大方块腾空间。", "注意共用一个出口的方块——它们通常需要按特定顺序出去。", "卡住了就撤回，从最下面的门倒推顺序。"], "medium": ["动第一步之前，提前规划好三步以上。", "把挡路的方块当作“临时停车”，先挪开再放回去。", "L 型和 T 型方块通常是关卡的“枢纽”，优先围绕它们破局。", "两种颜色抢同一条通道时，选路径完全空旷的那个先走。", "用预览确认方块真的能进入目标门，再下决定。"], "hard": ["动第一步之前，先在心里过一遍每个门的撤离顺序。", "长条方块需要“跑道”，先清出横向或纵向的空间。", "如果某个方块只有一条出路，就把那条路留到最后。", "为了让别的方块过去，把当前方块倒退一两格也是允许的。", "把“枢纽”方块——位于最密集角落的那个——留到最后处理。"], "expert": ["找出棋盘上的“瓶颈点”，所有方案都要绕开它。", "有些方块要动两次：先腾路，再回到它的门。", "把视频调成 0.5 倍速，注意那些看似一步的微调。", "如果两个方块各自只有一条出路，通常只有一种正确顺序。", "前 4 步如果偏离最优解，立即重开会更省时间。"], "super-hard": ["把视频前 5 步逐帧暂停看——那决定了整套方案。", "找出“锁定方块”（卡住所有东西的那个），算清它什么时候能动。", "超难关卡常常需要一个方块往返穿越整个棋盘，提前规划往返路线。", "中途卡住时，问题通常出在第 2、3 步，不是第 10 步。", "把每种颜色看成一条线索，按依赖顺序而不是视觉顺序逐个破解。"]},
  ja: {"easy": ["動かす前に、各ブロックの色と対応する扉を確認しましょう。", "小さなブロックから動かして、大きなブロックの動線を作ります。", "同じ扉を共有するブロックは、出す順番に注意。", "詰まったら一手戻し、下の扉から逆算しましょう。"], "medium": ["最初の一手を打つ前に、3手先まで計画しましょう。", "邪魔なブロックは『駐車スペース』と考えて、いったん退避させます。", "L字・T字のブロックがパズルの軸になることが多いので、優先的に処理。", "同じ通路を奪い合う色があれば、完全に開いている方を先に通します。", "動かす前にプレビューで、扉に本当に入るかを確認。"], "hard": ["最初の一手の前に、各扉からの脱出順を頭の中で組み立てましょう。", "長いブロックには『滑走路』が必要——縦か横の空間を先に確保。", "出口が一つしかないブロックは、その通路を最後まで空けておきます。", "他のブロックを通すために、一旦戻すのも有効な手。", "最も密集した角にある『要』のブロックは最後に。"], "expert": ["盤面のボトルネックを特定し、すべての解法はそこを避けます。", "ブロックを2回動かす必要があることも——通路を作って、戻す。", "動画を0.5倍速にすると、見落としがちな小さな動きが見えます。", "出口が一つしかないブロックが2つあれば、正解の順序は基本ひとつ。", "最初の4手が最適でないなら、すぐリセットした方が早い。"], "super-hard": ["動画の最初の5手をコマ送りで——ここで解法が決まります。", "全体を縛っている『ロック』ブロックを見つけ、いつ動かせるかを計算。", "超高難度では、1つのブロックが盤面を2往復することがよくあります。", "途中で詰まる原因は、たいてい2手目か3手目にあります。", "色ごとに『線』として扱い、見た目ではなく依存順で解いていきます。"]},
};

export const FAQ_BANK = {
  en: [{"q": "Why does this level look easier in the video than in my game?", "a": "Block Out level layouts are deterministic per level number. If your board looks different, double-check that you're on the same level — Daily Challenge and Event boards reuse level numbers."}, {"q": "How do I rotate or flip pieces?", "a": "Block Out doesn't support rotation. The shape you see is the shape you have to slide. Plan around the orientation."}, {"q": "Can I undo a wrong move?", "a": "Yes — tap the undo button after a misstep. Each level allows unlimited undos until you complete it. There's no penalty."}, {"q": "What if I'm running out of moves?", "a": "Restart the level instead of burning hints. Most levels can be solved in well under the move limit once you know the order."}],
  cn: [{"q": "为什么视频里看起来更简单？", "a": "Block Out 的关卡布局对每个关卡号是固定的。如果你的棋盘不一样，检查是不是同一关——每日挑战和活动会复用关卡号。"}, {"q": "可以旋转或翻转方块吗？", "a": "Block Out 不支持旋转。看到的形状就是你要滑的形状，按它的朝向规划。"}, {"q": "走错了能撤销吗？", "a": "可以，点撤销按钮就行。每关无限次撤销，没有惩罚。"}, {"q": "步数快用完了怎么办？", "a": "重开比用提示更划算。绝大多数关卡只要找到顺序，远远用不完步数。"}],
  ja: [{"q": "動画の方が簡単に見えるのはなぜ？", "a": "Block Outのレベル配置はレベル番号ごとに固定です。盤面が違うなら、同じレベルか確認を——デイリーチャレンジやイベントは番号が重複します。"}, {"q": "ブロックを回転できますか？", "a": "Block Outに回転はありません。見たままの形でスライドする必要があります。"}, {"q": "操作ミスを取り消せますか？", "a": "はい、Undoボタンで戻せます。各レベル無制限、ペナルティなし。"}, {"q": "手数が足りなくなったら？", "a": "ヒントを使うよりリスタートの方が早い。順番が分かれば、ほとんどのレベルは制限手数に余裕があります。"}],
};
